- name: Become at Play level
  hosts: default
  remote_user: vagrant
  # Fix problem with shell PATH incomplete.
  become: yes
  become_method: sudo
  become_flags: "--login"

  roles:

  tasks:
  - name: Check
    ansible.builtin.shell: echo $PATH #which code
    args:
      executable: "/usr/bin/bash"  #"{{bash}}"
    register: which

  - debug:
      msg: "{{which.stdout}}"
