- hosts: localhost
  vars:
    interface: 'enp1s0'
    get_interface: "{{ lookup('vars', 'ansible_' + interface) }}"

tasks:
  - ansible.builtin.debug:
    msg: "{{ get_interface }}"

# from: https://www.reddit.com/r/ansible/comments/bt14b0/question_how_to_create_dynamic_variable_names/
